# Generated by Django 2.2.4 on 2019-08-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190828_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downvotes_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.TextField(),
        ),
    ]
